In [2]:
import os, sys, importlib
import pandas as pd
import numpy as np
sys.path.append(os.path.abspath(".."))
from utils import modeling

## test:

In [3]:
path_listings_filtered="mod_results\listings_tactics_filtered.csv"
df_raw=pd.read_csv(path_listings_filtered)
df=df_raw.copy()
print(len(df))
print(df.columns)
display(df.head())

37013
Index(['Unnamed: 0', 'id', 'listing_url', 'scrape_id', 'last_scraped',
       'source', 'name', 'description', 'neighborhood_overview', 'picture_url',
       ...
       'auto_promotion_weighted', 'exemplarité_weighted', 'has_rating',
       'years_since_host', 'has_since', 'lang', 'len', 'has_response_rate',
       'professional_host', 'booking_rate_l30d'],
      dtype='object', length=117)

,Unnamed: 0,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,...,auto_promotion_weighted,exemplarité_weighted,has_rating,years_since_host,has_since,lang,len,has_response_rate,professional_host,booking_rate_l30d
0,0,3109.0,https://www.airbnb.com/rooms/3109,2.023121e+13,2023-12-12,city scrape,Rental unit in Paris · ★5.0 · 1 bedroom · 1 be...,NaN,Good restaurants<br />very close the Montparna...,https://a0.muscache.com/pictures/baeae9e2-cd53...,...,NaN,NaN,1,16.0,1,no_text,0,1,0,0.000000
1,2,81106.0,https://www.airbnb.com/rooms/81106,2.023121e+13,2023-12-13,city scrape,Rental unit in Paris · ★4.84 · 1 bedroom · 1 b...,NaN,The neighborhood will show you an other side o...,https://a0.muscache.com/pictures/miso/Hosting-...,...,0.606779,-0.441423,1,13.0,1,en,47,1,0,0.000000
2,3,7397.0,https://www.airbnb.com/rooms/7397,2.023121e+13,2023-12-13,city scrape,Rental unit in Paris · ★4.73 · 2 bedrooms · 2 ...,NaN,NaN,https://a0.muscache.com/pictures/67928287/330b...,...,-1.456089,-0.778443,1,16.0,1,en,10,1,1,0.333333
3,5,81615.0,https://www.airbnb.com/rooms/81615,2.023121e+13,2023-12-13,city scrape,Rental unit in Paris · ★4.74 · 1 bedroom · 1 b...,NaN,NaN,https://a0.muscache.com/pictures/2630947/9340f...,...,-0.546908,0.839862,1,13.0,1,en,101,1,0,0.000000
4,9,86053.0,https://www.airbnb.com/rooms/86053,2.023121e+13,2023-12-13,city scrape,Rental unit in Paris · ★4.88 · 1 bedroom · 2 b...,NaN,The flat is situated in the very heart of Pari...,https://a0.muscache.com/pictures/1982057/f94cf...,...,1.246919,0.084940,1,14.0,1,en,159,1,0,0.000000

In [4]:
# all_host_vars= ['host_picture_url', 'host_identity_verified', 'number_of_reviews', 'host_is_superhost',
#            'review_scores_rating', 'has_rating', 'host_since', 'years_since_host', 'host_about', 
#            'has_host_about', 'lang', 'len', 'host_response_time', 'host_response_rate', 'has_response_rate',
#            'calculated_host_listings_count', 'professional_host']
group_col='host_is_superhost'

host_vars= ['number_of_reviews', 'review_scores_rating', 'has_rating', 
        'host_since', 'years_since_host', 'host_about', 'has_host_about', 'lang', 'len',
        'host_response_time', 'host_response_rate', 'has_response_rate',
        'professional_host']

proxy_obj_vars=['price', "availability_30", "number_of_reviews_l30d","booking_rate_l30d",
        "room_type", "minimum_nights","instant_bookable"]

cols_tactics=['ouverture_mean',"authenticité_mean","sociabilité_mean", "auto_promotion_mean","exemplarité_mean",
        "ouverture_weighted", "authenticité_weighted","sociabilité_weighted","auto_promotion_weighted","exemplarité_weighted",
        ]

In [ ]:
##VIF: vérifier la corélation entre les variables:
from statsmodels.tools.tools import add_constant
from statsmodels.stats.outliers_influence import variance_inflation_factor
from patsy import dmatrices

# formula=('booking_rate_l30d ~ C(langue) + C(host_is_superhost) + C(professional_host) +'
# ' yrs_experience + C(host_identity_verified)+ C(host_has_profile_pic) +'
# ' availability_30 + price + review_scores_rating + '
# 'C(host_location_category) + C(property_type_category) + C(instant_bookable) + '
# 'len + openness +authenticity + sociability + self_promotion + exemplification ')


# formula=('booking_rate_l30d ~'
#         'C(host_identity_verified)+ C(host_has_profile_pic) +' 
#         'number_of_reviews + review_scores_rating + C(has_rating) +' 
#         ' years_since_host + C(has_host_about)+ C(lang) + len +'
#         'C (host_response_time) + host_response_rate + C(has_response_rate) + C(professional_host) +'
#         'price + booking_rate_l30d + C(room_type) + minimum_nights + C(instant_bookable)+'
#         'ouverture_mean + authenticité_mean + sociabilité_mean + auto_promotion_mean + exemplarité_mean'
# )


# has_host_about在lang:no_text中重复了
# review_scores_rating的0 和has_raitng重复

formula=('booking_rate_l30d ~'
        'number_of_reviews + review_scores_rating +' 
        ' years_since_host + C(lang) + len + C(professional_host) + C(host_is_superhost)+'
        'price + C(room_type) + minimum_nights + C(instant_bookable)+'
        'ouverture_mean + authenticité_mean + sociabilité_mean + auto_promotion_mean + exemplarité_mean'
)


y, X = dmatrices(formula, data=df, return_type='dataframe')
vif_df = pd.DataFrame()
vif_df['Variables']=X.columns
vif_df["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif_df['niveau_colinearite'] = vif_df["VIF"].apply(
    lambda x: " " if x <= 1 else
              "*" if x <= 5 else
              "**" if x <= 10 else
              "***"
)
display(vif_df)

d:\miniconda3\envs\airbnb_env\lib\site-packages\statsmodels\regression\linear_model.py:1782: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
d:\miniconda3\envs\airbnb_env\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

                          Variables           VIF niveau_colinearite
0                         Intercept  1.608709e+04                ***
1                     C(lang)[T.fr]  1.252065e+00                  *
2                C(lang)[T.no_text]           NaN                ***
3            C(lang)[T.other_langs]  1.024817e+00                  *
4         C(professional_host)[T.1]  1.381972e+00                  *
5         C(host_is_superhost)[T.f]           inf                ***
6         C(host_is_superhost)[T.t]           inf                ***
7   C(room_type)[T.Entire home/apt]           inf                ***
8        C(room_type)[T.Hotel room]           inf                ***
9      C(room_type)[T.Private room]           inf                ***
10      C(room_type)[T.Shared room]           inf                ***
11         C(instant_bookable)[T.t]  1.291542e+00                  *
12                number_of_reviews  1.130858e+00                  *
13             review_scores_rating  1.158258e+00                  *
14                 years_since_host  1.245034e+00                  *
15                              len  1.366580e+00                  *
16                            price  1.051685e+00                  *
17                   minimum_nights  1.055128e+00                  *
18                   ouverture_mean  1.711625e+00                  *
19                authenticité_mean  1.875667e+00                  *
20                 sociabilité_mean  1.596695e+00                  *
21              auto_promotion_mean  2.072859e+00                  *
22                 exemplarité_mean  1.410638e+00                  *

In [59]:
df.host_is_superhost.value_counts(dropna=False)

host_is_superhost
f                     29280
t                      7733
Entire rental unit        1
Name: count, dtype: int64

In [ ]:
# model1=smf.ols('booking_rate_l30d ~ C(langue) + C(host_is_superhost) + C(professional_host) +'
# ' yrs_experience + C(host_identity_verified)+ C(host_has_profile_pic) +'#host_response_rate+
# ' availability_30 + price + review_scores_rating + '
# 'C(host_location_category) + C(property_type_category)+ C(instant_bookable) + '#+ beds +bathrooms+
# 'len + len_squared', data=df).fit()

# 'booking_rate_l30d ~'
# 'number_of_reviews + review_scores_rating +' 
# ' years_since_host + C(lang) + len + C(professional_host) +'
# 'price + C(room_type) + minimum_nights + C(instant_bookable)+'

        
model_basic=smf.ols('booking_rate_l30d ~'
        'number_of_reviews + review_scores_rating + C(has_rating) +' 
        ' years_since_host +'
        'C(professional_host) +'
        'price + C(room_type) + minimum_nights + C(instant_bookable)'
        , data=df).fit()

print(model_basic.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      booking_rate_l30d   R-squared:                       0.144
Model:                            OLS   Adj. R-squared:                  0.143
Method:                 Least Squares   F-statistic:                     259.3
Date:                Wed, 10 Dec 2025   Prob (F-statistic):               0.00
Time:                        17:41:36   Log-Likelihood:                 8549.2
No. Observations:               37012   AIC:                        -1.705e+04
Df Residuals:                   36987   BIC:                        -1.684e+04
Df Model:                          24
Covariance Type:            nonrobust
===============================================================================================================
                                                  coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------
Intercept                                      -0.0030      0.035     -0.086      0.931      -0.071       0.065
C(host_identity_verified)[T.f]                 -0.0285      0.046     -0.626      0.531      -0.118       0.061
C(host_identity_verified)[T.t]                 -0.0328      0.045     -0.722      0.470      -0.122       0.056
C(host_has_profile_pic)[T.f]                   -0.0316      0.046     -0.693      0.488      -0.121       0.058
C(host_has_profile_pic)[T.t]                   -0.0298      0.045     -0.655      0.513      -0.119       0.059
C(has_rating)[T.1]                             -0.0888      0.013     -6.923      0.000      -0.114      -0.064
C(has_host_about)[T.1]                          0.0152      0.019      0.794      0.427      -0.022       0.053
C(lang)[T.fr]                                   0.0128      0.003      4.184      0.000       0.007       0.019
C(lang)[T.no_text]                              0.0302      0.019      1.574      0.115      -0.007       0.068
C(lang)[T.other_langs]                          0.0147      0.010      1.454      0.146      -0.005       0.035
C(host_response_time)[T.no_response_time]       0.0403      0.080      0.507      0.612      -0.116       0.196
C(host_response_time)[T.within a day]          -0.0241      0.010     -2.314      0.021      -0.045      -0.004
C(host_response_time)[T.within a few hours]    -0.0067      0.011     -0.591      0.555      -0.029       0.016
C(host_response_time)[T.within an hour]         0.0313      0.011      2.728      0.006       0.009       0.054
C(has_response_rate)[T.1]                       0.0150      0.080      0.188      0.851      -0.141       0.171
C(professional_host)[T.1]                      -0.0054      0.002     -2.297      0.022      -0.010      -0.001
C(room_type)[T.Entire home/apt]                 0.0110      0.023      0.478      0.633      -0.034       0.056
C(room_type)[T.Hotel room]                     -0.0669      0.024     -2.807      0.005      -0.114      -0.020
C(room_type)[T.Private room]                    0.0147      0.023      0.640      0.522      -0.030       0.060
C(room_type)[T.Shared room]                    -0.0201      0.025     -0.818      0.414      -0.068       0.028
C(instant_bookable)[T.t]                       -0.0070      0.003     -2.757      0.006      -0.012      -0.002
number_of_reviews                               0.0009   1.72e-05     52.150      0.000       0.001       0.001
review_scores_rating                            0.0325      0.003     12.007      0.000       0.027       0.038
years_since_host                               -0.0037      0.000    -11.638      0.000      -0.004      -0.003
len                                         -4.588e-05   1.74e-05     -2.639      0.008      -8e-05   -1.18e-05
host_response_rate                              0.0534      0.012      4.441      0.000       0.030       0.077
price                                       -6.059e-06    1.5e-06     -4.034      0.000      -9e-06   -3.11e-06
minimum_nights                              -9.366e-05   1.42e-05     -6.599      0.000      -0.000   -6.58e-05
==============================================================================
Omnibus:                    22901.321   Durbin-Watson:                   1.958
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           219563.791
Skew:                           2.937   Prob(JB):                         0.00
Kurtosis:                      13.386   Cond. No.                     1.08e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.6e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
formula='booking_rate_l30d ~'
        'C(host_identity_verified)+ C(host_has_profile_pic) +' 
        'number_of_reviews + review_scores_rating + C(has_rating) +' 
        ' years_since_host + C(has_host_about)+ C(lang) + len +'
        'C (host_response_time) + host_response_rate + C(has_response_rate) + C(professional_host) +'
        'price + C(room_type) + minimum_nights + C(instant_bookable)+'
# "ouverture_mean + authenticité_mean + sociabilité_mean + auto_promotion_mean + exemplarité_mean"

vars_tactics=['ouverture_mean',"authenticité_mean","sociabilité_mean", "auto_promotion_mean","exemplarité_mean"]
formula+='+'.join(vars_tactics)
print(f"[INFO] formula : {formula}")


model_tactics_mean=smf.ols(formula, data=df).fit()
print(model_tactics_mean.summary())

IndentationError: unexpected indent (2292026982.py, line 2)

In [ ]:
'ouverture_mean',"authenticité_mean","sociabilité_mean", "auto_promotion_mean","exemplarité_mean",

In [ ]:
# model_tactics_weighted=smf.ols('booking_rate_l30d ~'
#         'C(host_identity_verified)+ C(host_has_profile_pic) +' 
#         'number_of_reviews + review_scores_rating + C(has_rating) +' 
#         ' years_since_host + C(has_host_about)+ C(lang) + len +'
#         'C (host_response_time) + host_response_rate + C(has_response_rate) + C(professional_host) +'
#         'price + C(room_type) + minimum_nights + C(instant_bookable)+'
#         "ouverture_weighted + authenticité_weighted + sociabilité_weighted + auto_promotion_weighted + exemplarité_weighted"
#         , data=df).fit()
# print(model_tactics_weighted.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      booking_rate_l30d   R-squared:                       0.169
Model:                            OLS   Adj. R-squared:                  0.167
Method:                 Least Squares   F-statistic:                     120.5
Date:                Wed, 10 Dec 2025   Prob (F-statistic):               0.00
Time:                        17:46:14   Log-Likelihood:                 3609.6
No. Observations:               16081   AIC:                            -7163.
Df Residuals:                   16053   BIC:                            -6948.
Df Model:                          27
Covariance Type:            nonrobust
===============================================================================================================
                                                  coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------
Intercept                                       0.0030      0.025      0.122      0.903      -0.045       0.051
C(host_identity_verified)[T.f]                 -0.0288      0.049     -0.584      0.559      -0.126       0.068
C(host_identity_verified)[T.t]                 -0.0257      0.049     -0.522      0.601      -0.122       0.071
C(host_has_profile_pic)[T.f]                   -0.0290      0.052     -0.553      0.580      -0.132       0.074
C(host_has_profile_pic)[T.t]                   -0.0255      0.050     -0.512      0.608      -0.123       0.072
C(has_rating)[T.1]                             -0.0951      0.021     -4.633      0.000      -0.135      -0.055
C(has_host_about)[T.1]                          0.0030      0.025      0.122      0.903      -0.045       0.051
C(lang)[T.fr]                                   0.0101      0.004      2.860      0.004       0.003       0.017
C(lang)[T.no_text]                          -1.114e-16    1.6e-16     -0.697      0.486   -4.25e-16    2.02e-16
C(lang)[T.other_langs]                         -0.0003      0.018     -0.016      0.987      -0.036       0.035
C(host_response_time)[T.no_response_time]       0.0392      0.073      0.536      0.592      -0.104       0.183
C(host_response_time)[T.within a day]          -0.0291      0.018     -1.662      0.096      -0.063       0.005
C(host_response_time)[T.within a few hours]    -0.0144      0.019     -0.754      0.451      -0.052       0.023
C(host_response_time)[T.within an hour]         0.0215      0.019      1.122      0.262      -0.016       0.059
C(has_response_rate)[T.1]                       0.0212      0.073      0.289      0.772      -0.123       0.165
C(professional_host)[T.1]                       0.0082      0.004      2.239      0.025       0.001       0.015
C(room_type)[T.Entire home/apt]                 0.0139      0.025      0.552      0.581      -0.036       0.063
C(room_type)[T.Hotel room]                     -0.0652      0.026     -2.466      0.014      -0.117      -0.013
C(room_type)[T.Private room]                    0.0236      0.025      0.929      0.353      -0.026       0.073
C(room_type)[T.Shared room]                    -0.0269      0.032     -0.839      0.401      -0.090       0.036
C(instant_bookable)[T.t]                       -0.0009      0.004     -0.226      0.822      -0.008       0.007
number_of_reviews                               0.0009    2.2e-05     41.633      0.000       0.001       0.001
review_scores_rating                            0.0316      0.004      7.316      0.000       0.023       0.040
years_since_host                               -0.0045      0.001     -9.055      0.000      -0.006      -0.004
len                                         -3.042e-05   2.02e-05     -1.503      0.133   -7.01e-05    9.25e-06
host_response_rate                              0.0544      0.020      2.740      0.006       0.015       0.093
price                                       -7.739e-06   2.69e-06     -2.880      0.004    -1.3e-05   -2.47e-06
minimum_nights                                 -0.0001   2.34e-05     -4.322      0.000      -0.000   -5.53e-05
ouverture_weighted                             -0.0018      0.002     -0.915      0.360      -0.006       0.002
authenticité_weighted                           0.0067      0.002      3.024      0.002       0.002       0.011
sociabilité_weighted                            0.0036      0.002      1.836      0.066      -0.000       0.007
auto_promotion_weighted                        -0.0047      0.002     -2.005      0.045      -0.009      -0.000
exemplarité_weighted                            0.0006      0.002      0.307      0.759      -0.003       0.004
==============================================================================
Omnibus:                     9615.290   Durbin-Watson:                   1.942
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            86288.935
Skew:                           2.826   Prob(JB):                         0.00
Kurtosis:                      12.841   Cond. No.                     1.15e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.97e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.